services:
    App\EventListener\LogoutSuccessListener:
        tags:
            - { name: kernel.event_listener, event: Symfony\Component\Security\Http\Event\LogoutEvent, method: onLogoutSuccess }

    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
